CREATE TABLE UYELER(
	Uye_no INT IDENTITY(1,1),
	Uye_soyadi VARCHAR(25),
	Cinsiyet VARCHAR(7),
	Telefon VARCHAR(11),
	E_posta VARCHAR(40),
	Adres_no INT,
	PRIMARY KEY("Uye_no")
);

CREATE TABLE ADRESLER(
	Adres_no INT IDENTITY(1,1),
	Cadde VARCHAR(10),
	Mahalle VARCHAR(10),
	Bina_no VARCHAR(5),
	Sehir VARCHAR(15),
	Posta_kodu INT, 
	Ulke VARCHAR(20),
	PRIMARY KEY ("Adres_no")
);

ALTER TABLE UYELER ADD CONSTRAINT "ADRESLER_UYELER" 
FOREIGN KEY (Adres_no) REFERENCES ADRESLER(Adres_no);

CREATE TABLE EMANET(
	Emanet_no INT IDENTITY(1,1),
	ISBN VARCHAR(30) NOT NULL,
	Uye_no INT NOT NULL,
	Kutuphane_no INT NOT NULL,
	Emanet_tarihi DATETIME,
	Teslim_tarihi DATETIME,
	PRIMARY KEY ("Emanet_no")
);

CREATE TABLE KITAPLAR(
	ISBN VARCHAR(30),
	Kitap_adi VARCHAR(20),
	Yayin_tarihi VARCHAR(10),
	Sayfa_sayisi INT,
	PRIMARY KEY ("ISBN")
);

CREATE TABLE YAZARLAR(
	YazarNo INT IDENTITY(1,1),
	YazarAdi VARCHAR(20),
	YazarSoyadi VARCHAR(20),
	PRIMARY KEY ("YazarNo")
);

CREATE TABLE KATEGORILER(
	Kategori_no INT IDENTITY(1,1),
	Kategori_adi VARCHAR(20),
	PRIMARY KEY ("Kategori_no")
);

CREATE TABLE KUTUPHANE(
	Kutuphane_no INT IDENTITY(1,1),
	Kutuphane_adi VARCHAR(20),
	Adres_no INT,
	PRIMARY KEY ("Kutuphane_no")
);

CREATE TABLE KITAP_KUTUPHANE(
	Kutuphane_no INT NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	Miktar INT,
	CONSTRAINT "KITAP_KUTUPHANE_PK" PRIMARY KEY ("Kutuphane_no", "ISBN"),
	CONSTRAINT "KITAP_KUTUPHANE_FK" FOREIGN KEY ("Kutuphane_no") REFERENCES KATEGORILER(Kategori_no)

);


CREATE TABLE KITAP_KATEGORI(
	ISBN VARCHAR(20) NOT NULL,
	Kategori_no INT NOT NULL,
	CONSTRAINT "KITAP_KATEGORI_PK" PRIMARY KEY ("Kategori_no", "ISBN")
);

CREATE TABLE KITAP_YAZAR(
	ISBN VARCHAR(20) NOT NULL,
	Yazar_no INT NOT NULL,
	CONSTRAINT "KITAP_YAZAR_PK" PRIMARY KEY ("Yazar_no", "ISBN")
);


Select * From ADRESLER Where Adres_no ='1' 

